name: Python test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    runs-on: ubuntu-20.04
    env:
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
      REGION_ID: ${{ vars.REGION_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      ROOT_UID: ${{ secrets.ROOT_UID }}
      CONCURRENT_ID: "${{ github.run_number }}${{ strategy.job-index }}"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        pip install unittest2
        pip install coverage
        pip install pycodestyle
        pip install mock
        pip install jmespath cryptography
        pip install pytest
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
        make coverage-report
        test -z $ACCESS_KEY_ID -a -z $ACCESS_KEY_SECRET || make functional-test
        bash <(curl -s https://codecov.io/bash)
